name: update Caddy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (optional, for context)
        uses: actions/checkout@v4

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy via SSH with password
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            echo "\n\n-----------------------------------------------------------------------"
            echo "Entering Project Folder"
            cd ${{ secrets.WORK_DIR }}
            git pull origin ${{ secrets.MAIN_BRANCH }}
          
          
            echo "\n\n-----------------------------------------------------------------------"
            echo "Restarting Caddy"
            sudo docker compose restart caddy
            echo "\n\n------------------------------------------------------------------------"
            echo "                       SCRIPT SUCCEEDED SUCCESSFULLY :-)                    "
            echo "----------------------------------------------------------------------------"
          EOF